name: PotatoFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 3.1
description: Plugin for the PotatoFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, DisguiseCraft, BarAPI, CoreProtect]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, tylerhyperHD, reuben4545, AlexTheMurderer]

# plugin.yml is no longer used to define commands.
